name: Release on Push

# Automatically creates GitHub releases after release PRs are merged

on:
  push:
    branches:
      - main
      - beta
      # - alpha  # Uncomment if you have an alpha channel

jobs:
  create-release:
    uses: heroku/npm-release-workflows/.github/workflows/release-on-push.yml@main
    with:
      runs_on: sfdc-hk-ubuntu-latest  # Options: ubuntu-latest | sfdc-hk-ubuntu-latest | pub-hk-ubuntu-24.04-ip
      package_manager: yarn  # Options: npm | yarn | pnpm
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
